window.MotorasShop = (() => {
  const footerHtml = `
  <footer class="common-footer shop-footer">
    <div class="in">
      <div class="common-footer-grid">
        <div><h4>Motoraș</h4><p>Piese auto originale și aftermarket, livrare rapidă și suport clar înainte și după comandă.</p><p><a href="despre.html">Despre Motoraș</a></p><p><a href="faq.html">Întrebări frecvente</a></p></div>
        <div><h4>Magazin</h4><p><a href="category.html?cat=piese">Piese auto</a></p><p><a href="category.html?cat=filtre">Filtre</a></p><p><a href="category.html?cat=uleiuri">Uleiuri</a></p><p><a href="search.html?q=bosch">Caută produse</a></p></div>
        <div><h4>Ajutor</h4><p><a href="livrare.html">Livrare &amp; plată</a></p><p><a href="retururi.html">Retururi</a></p><p><a href="contact.html">Contact</a></p><p><a href="faq.html">FAQ</a></p></div>
        <div><h4>Cont &amp; admin</h4><p><a href="account.html">Contul meu</a></p><p><a href="confirmation.html">Status comandă</a></p><p><a href="admin.html">Dashboard admin</a></p><p><a href="cookies.html">Cookies</a></p></div>
      </div>
      <div class="bottom"><span>© 2026 Motoraș · piese auto, accesorii și consumabile pentru întreținerea mașinii</span><span><a href="https://anpc.ro/ce-este-sal/" target="_blank" rel="noopener">ANPC SAL</a> · <a href="https://ec.europa.eu/consumers/odr" target="_blank" rel="noopener">SOL UE</a></span></div>
    </div>
  </footer>`;
  const PAGE_SIZE = 9;
  function injectShopFooters(){document.querySelectorAll('[data-shop-footer]').forEach(el=>el.outerHTML=footerHtml)}
  function updateCart(){ if(!window.MotorasStore) return; const cart=window.MotorasStore.getCart(); const total=window.MotorasStore.getCartTotal(); const count=window.MotorasStore.getCartCount(); document.querySelectorAll('#cartBadge, #cartItemCount, .cart-count').forEach(el=>{ if(el.id==='cartItemCount') el.textContent=count>0?`(${count})`:''; else el.textContent=count; }); const container=document.getElementById('cartItems'); const empty=document.getElementById('cartEmpty'); const footer=document.getElementById('cartFooter'); if(!container) return; if(cart.length===0){ if(empty) empty.style.display='flex'; if(footer) footer.style.display='none'; container.innerHTML=''; if(empty) container.appendChild(empty);} else { if(empty) empty.style.display='none'; if(footer) footer.style.display='block'; container.innerHTML=cart.map(item=>`<div class="cart-item"><div class="ci-img"><img src="${item.img}" alt="${item.name}"/></div><div class="ci-info"><div class="ci-brand">${item.brand}</div><div class="ci-name">${item.name}</div><div class="ci-row"><div class="ci-qty"><button onclick="window.MotorasShop.changeQty('${item.id}',-1)">&#8722;</button><span>${item.qty}</span><button onclick="window.MotorasShop.changeQty('${item.id}',1)">+</button></div><span class="ci-price">${window.MotorasStore.formatPrice(item.price*item.qty)}</span><button class="ci-remove" onclick="window.MotorasShop.removeFromCart('${item.id}')">×</button></div></div></div>`).join(''); } const st=document.getElementById('cartSubtotal'); const ct=document.getElementById('cartTotal'); if(st) st.textContent=window.MotorasStore.formatPrice(total); if(ct) ct.textContent=window.MotorasStore.formatPrice(total); }
  function openCart(){const d=document.getElementById('cartDrawer'); const o=document.getElementById('cartOverlay'); if(d) d.classList.add('open'); if(o) o.classList.add('open'); document.body.style.overflow='hidden'}
  function closeCart(){const d=document.getElementById('cartDrawer'); const o=document.getElementById('cartOverlay'); if(d) d.classList.remove('open'); if(o) o.classList.remove('open'); document.body.style.overflow=''}
  function addCatalogProduct(productId){const p=window.MotorasCatalog?.getProductById(productId); if(!p||!window.MotorasStore) return; window.MotorasStore.addToCart(p.name,p.brand,p.price,p.img,p.id); updateCart(); if(document.getElementById('cartDrawer')) openCart();}
  function addToCart(name,brand,price,img,id=null){if(!window.MotorasStore) return; window.MotorasStore.addToCart(name,brand,price,img,id); updateCart(); if(document.getElementById('cartDrawer')) openCart();}
  function removeFromCart(id){window.MotorasStore.removeFromCart(id); updateCart();}
  function changeQty(id,delta){window.MotorasStore.changeQty(id,delta); updateCart();}
  function goCheckout(){if(!window.MotorasStore?.getCart().length){alert('Coșul este gol.'); return;} closeCart(); window.location.href='checkout.html';}
  function toggleMobSearch(){const bar=document.getElementById('mobSearchBar'); const t=document.getElementById('mobSearchToggle'); if(!bar) return; const isOpen=bar.style.display==='flex'; bar.style.display=isOpen?'none':'flex'; if(t) t.classList.toggle('active',!isOpen); if(!isOpen) setTimeout(()=>bar.querySelector('input')?.focus(),80);}
  function attachGlobalSearch(){const desktop=document.getElementById('desktopSearchInput'); const mobile=document.querySelector('#mobSearchBar input'); [desktop,mobile].forEach(input=>{ if(!input) return; input.addEventListener('keydown',e=>{ if(e.key==='Enter'){ e.preventDefault(); const q=input.value.trim(); if(q) window.location.href=`search.html?q=${encodeURIComponent(q)}`; }}); });}
  function getCategoryFilters(){ const params=new URLSearchParams(location.search); const selectedBrands=[...document.querySelectorAll('#sidebarFilters input[type="checkbox"][id^="b"]:checked')].map(i=>i.nextElementSibling?.textContent?.trim()).filter(Boolean); return { cat:params.get('cat')||'piese', brands:selectedBrands, min:Number(document.getElementById('pMin')?.value||0), max:Number(document.getElementById('pMax')?.value||0), inStock:!!document.getElementById('inStock')?.checked, onSale:!!document.getElementById('onSale')?.checked, sort:document.getElementById('sortSelect')?.value||'popular', page:Number(params.get('page')||1) }; }
  function applyProductFilters(products, filters){ let out=[...products]; if(filters.brands?.length) out=out.filter(p=>filters.brands.includes(p.brand)); if(filters.min) out=out.filter(p=>Number(p.price)>=filters.min); if(filters.max) out=out.filter(p=>Number(p.price)<=filters.max); if(filters.inStock) out=out.filter(p=>Number(p.stock)>0); if(filters.onSale) out=out.filter(p=>Number(p.old)>Number(p.price)); if(filters.sort==='price_asc') out.sort((a,b)=>a.price-b.price); else if(filters.sort==='price_desc') out.sort((a,b)=>b.price-a.price); else if(filters.sort==='rating') out.sort((a,b)=>(b.rating||0)-(a.rating||0)||((b.reviews||0)-(a.reviews||0))); else out.sort((a,b)=>(b.reviews||0)-(a.reviews||0)); return out; }
  function syncCategoryControls(filters){ const sort = document.querySelector('select'); if(sort){ sort.id='sortSelect'; sort.value=filters.sort; } }
  function renderActiveChips(host, filters){ if(!host) return; const chips=[]; filters.brands?.forEach(b=>chips.push(`<span class="motoras-chip">${b}</span>`)); if(filters.min) chips.push(`<span class="motoras-chip">de la ${filters.min} RON</span>`); if(filters.max) chips.push(`<span class="motoras-chip">până la ${filters.max} RON</span>`); if(filters.inStock) chips.push(`<span class="motoras-chip">În stoc</span>`); if(filters.onSale) chips.push(`<span class="motoras-chip">Reduceri</span>`); host.innerHTML=chips.join(''); host.style.display=chips.length?'flex':'none'; }
  function renderPager(container, total, current, onPage){ if(!container) return; const pages=Math.max(1,Math.ceil(total/PAGE_SIZE)); if(pages===1){container.innerHTML=''; return;} container.innerHTML=Array.from({length:pages},(_,i)=>`<button class="${i+1===current?'active':''}" data-page="${i+1}">${i+1}</button>`).join('')+`<button data-page="${Math.min(pages,current+1)}">Următor →</button>`; container.querySelectorAll('button').forEach(btn=>btn.onclick=()=>onPage(Number(btn.dataset.page))); }
  function updateCategoryUrl(filters, page=1){ const params=new URLSearchParams(); params.set('cat', filters.cat); if(page>1) params.set('page', page); history.replaceState({},'',`category.html?${params.toString()}`); }
  function renderCategoryPage(pageOverride){ const grid=document.getElementById('prodsGrid'); if(!grid||!window.MotorasCatalog||!window.MotorasRender) return; const catKey=new URLSearchParams(location.search).get('cat')||'piese'; const meta=window.MotorasCatalog.categories[catKey]||window.MotorasCatalog.categories.piese; const base=window.MotorasCatalog.byCategory(catKey); const filters=getCategoryFilters(); filters.cat=catKey; syncCategoryControls(filters); const products=applyProductFilters(base, filters); const currentPage=pageOverride||filters.page||1; const start=(currentPage-1)*PAGE_SIZE; const pageItems=products.slice(start,start+PAGE_SIZE); [['catBannerTitle',meta.title],['catBannerDesc',meta.desc],['catH1',meta.title],['bcCurrent',meta.title]].forEach(([id,val])=>{const el=document.getElementById(id); if(el) el.textContent=val;}); const img=document.getElementById('catBannerImg'); if(img) img.src=meta.img; const countEl=document.getElementById('catCount'); if(countEl) countEl.textContent=`${products.length} produse`; document.title=`${meta.title} – Motoraș`; let chipHost=document.getElementById('activeCategoryFilters'); if(!chipHost){ chipHost=document.createElement('div'); chipHost.id='activeCategoryFilters'; chipHost.className='motoras-toolbar__group'; const topRow=countEl?.parentElement?.parentElement; if(topRow) topRow.insertAdjacentElement('afterend', chipHost); } renderActiveChips(chipHost, filters); if(!products.length){ grid.innerHTML='<div class="motoras-empty">Nu există produse pentru filtrele selectate. Resetează filtrele și încearcă din nou.</div>'; } else { grid.innerHTML=pageItems.map(window.MotorasRender.productCard).join(''); }
    let pager=document.getElementById('categoryPager'); if(!pager){ pager=document.createElement('div'); pager.id='categoryPager'; pager.className='motoras-pager'; grid.parentElement.appendChild(pager);} renderPager(pager, products.length, currentPage, p=>{ updateCategoryUrl(filters,p); renderCategoryPage(p); window.scrollTo({top:grid.offsetTop-120,behavior:'smooth'});}); }
  function applyFilters(){ renderCategoryPage(1); }
  function clearFilters(){ document.querySelectorAll('#sidebarFilters input[type="checkbox"]').forEach(i=>i.checked=false); const pMin=document.getElementById('pMin'); const pMax=document.getElementById('pMax'); if(pMin) pMin.value='0'; if(pMax) pMax.value='1000'; const sort=document.getElementById('sortSelect'); if(sort) sort.value='popular'; renderCategoryPage(1); }
  function doSearch(){ const q=document.getElementById('searchInput')?.value?.trim(); const brand=document.getElementById('searchBrandFilter')?.value||''; const sort=document.getElementById('searchSort')?.value||'popular'; const stock=document.getElementById('searchStockOnly')?.checked ? '1' : ''; const params=new URLSearchParams(); if(q) params.set('q', q); if(brand) params.set('brand', brand); if(sort && sort!=='popular') params.set('sort', sort); if(stock) params.set('stock', stock); window.location.href=`search.html?${params.toString()}`; }
  function injectSearchToolbar(results){ const grid=document.getElementById('resultsGrid'); if(!grid||document.getElementById('searchToolbar')) return; const brands=window.MotorasCatalog.brands(); const toolbar=document.createElement('div'); toolbar.id='searchToolbar'; toolbar.className='motoras-filter-card'; toolbar.innerHTML=`<div class="motoras-filter-grid"><select id="searchBrandFilter" class="motoras-select"><option value="">Toate mărcile</option>${brands.map(b=>`<option value="${b}">${b}</option>`).join('')}</select><select id="searchSort" class="motoras-select"><option value="popular">Cele mai populare</option><option value="price_asc">Preț crescător</option><option value="price_desc">Preț descrescător</option><option value="rating">Rating</option></select><label class="motoras-chip" style="justify-content:center"><input type="checkbox" id="searchStockOnly" style="accent-color:var(--red)"> Doar în stoc</label><button class="motoras-select" style="background:var(--red);color:#fff;border-color:var(--red);cursor:pointer" onclick="window.MotorasShop.doSearch()">Aplică filtre</button></div>`; grid.parentElement.insertBefore(toolbar, grid); }
  function renderSearchPage(){ const grid=document.getElementById('resultsGrid'); if(!grid||!window.MotorasCatalog||!window.MotorasRender) return; const params=new URLSearchParams(location.search); const q=params.get('q')||''; const brand=params.get('brand')||''; const sort=params.get('sort')||'popular'; const stock=params.get('stock')==='1'; const title=document.getElementById('searchTitle'); const sub=document.getElementById('searchSub'); const noQuery=document.getElementById('noQuery'); const noResults=document.getElementById('noResults'); const input=document.getElementById('searchInput'); if(input) input.value=q; injectSearchToolbar(); const bSel=document.getElementById('searchBrandFilter'); const sSel=document.getElementById('searchSort'); const st=document.getElementById('searchStockOnly'); if(bSel) bSel.value=brand; if(sSel) sSel.value=sort; if(st) st.checked=stock; if(!q){ if(noQuery) noQuery.style.display='block'; if(title) title.textContent='Caută produse'; if(sub) sub.textContent='Introdu un termen de căutare'; return; } let results=window.MotorasCatalog.search(q,{sort}); if(brand) results=results.filter(p=>p.brand===brand); if(stock) results=results.filter(p=>Number(p.stock)>0); document.title=`Caută: ${q} – Motoraș`; if(results.length){ if(noResults) noResults.style.display='none'; if(title) title.textContent=`Rezultate pentru "${q}"`; const info=[`${results.length} produse găsite`, brand?`marca ${brand}`:'', stock?'doar în stoc':''].filter(Boolean).join(' · '); if(sub) sub.textContent=info; grid.innerHTML=results.map(window.MotorasRender.productCard).join(''); } else { if(title) title.textContent=`Niciun rezultat pentru "${q}"`; if(sub) sub.textContent='Încearcă un termen mai general'; if(noResults) noResults.style.display='block'; const msg=document.getElementById('noResultsMsg'); if(msg) msg.textContent=`Nu am găsit rezultate pentru "${q}".`; grid.innerHTML=''; } }
  function renderRelatedProducts(){ const grid=document.getElementById('relatedGrid'); if(!grid||!window.MotorasCatalog||!window.MotorasRender) return; const pid=new URLSearchParams(location.search).get('id')||'p3'; const current=window.MotorasCatalog.getProductById(pid); if(!current) return; const related=window.MotorasCatalog.products.filter(p=>p.id!==current.id&&(p.cat===current.cat||p.brand===current.brand)).slice(0,4); if(related.length) grid.innerHTML=related.map(window.MotorasRender.productCard).join(''); }
  document.addEventListener('DOMContentLoaded',()=>{ injectShopFooters(); attachGlobalSearch(); renderCategoryPage(); renderSearchPage(); renderRelatedProducts(); updateCart(); document.addEventListener('keydown',e=>{if(e.key==='Escape') closeCart();}); const sort=document.querySelector('#sortSelect'); if(sort) sort.addEventListener('change',()=>renderCategoryPage(1)); });
  return { injectShopFooters, updateCart, openCart, closeCart, addToCart, addCatalogProduct, removeFromCart, changeQty, goCheckout, toggleMobSearch, renderCategoryPage, renderSearchPage, renderRelatedProducts, applyFilters, clearFilters, doSearch };
})();
window.openCart=window.MotorasShop.openCart; window.closeCart=window.MotorasShop.closeCart; window.addToCart=window.MotorasShop.addToCart; window.removeFromCart=window.MotorasShop.removeFromCart; window.changeQty=window.MotorasShop.changeQty; window.goCheckout=window.MotorasShop.goCheckout; window.toggleMobSearch=window.MotorasShop.toggleMobSearch; window.applyFilters=window.MotorasShop.applyFilters; window.clearFilters=window.MotorasShop.clearFilters; window.doSearch=window.MotorasShop.doSearch;
